### ISSUE TITLE
Database problem?

### ISSUE THREAD

**Issue by ritualz** [turi-inc/turi#3]
When you sync from this repo, there might be a problem with the database, but just run:

rake db:test:prepare
rake db:migrate

And it should work just fine

**Comment by fsauter** [comment]
What kind of problem? Related to the development/production thing we added for Heroku?

**Comment by ritualz** [comment]
When Kristoffer tried to fork the master he had some strange stuff coming up like try switching to RAILS_ENV(production). Might be the heroku stuff, but the rake commands did fix it.

**Comment by fsauter** [comment]
So fork, clone and run bundle install? Or during the rails -s command? How can I reproduce it?

**Comment by ritualz** [comment]
Rails s, should result in the error.

**Comment by fsauter** [comment]
I think we can close this issue since the migrate command is mandatory anyway?

**Comment by ritualz** [comment]
Sure thing...

**Comment by ritualz** [comment]
Sure thing...
